[package]
name = "rayon-logs-viewer"
version = "0.1.0"
authors = ["frederic wagner <frederic.wagner@univ-grenoble-alpes.fr>"]
edition = "2018"

[dependencies]
piston_window = "0.85.0"
rayon_logs={path="../rayon-logs"}
